### PR TITLE
FIX Opt-in performance fix for many consecutive lookups using isLocalisedInStage

### LINKED ISSUE #467: Allow caching and prepopulation for isLocalisedInStage
`FluentVersionedExtension::isLocalisedInStage()` is heavily used in the CMS, e.g. when rendering tree items.

In order to cut down on the query count on large sites, this value should be able to be cached and the cache prepopulated, as we do for page versions, and as I have recommended for Hierarchy::numChildren() in https://github.com/silverstripe/silverstripe-framework/issues/8379.

### PR DESCRIPTION
**Pull request by ScopeyNZ**
This PR adds a static method to pre-populate a cache of object IDs that exist in the given locale. This can be opted into by calling this method from appropriate user-code (or user-code extension) or alternatively by providing a list of classes that should be pre-populated (done when the first call of `isLocalisedInStage` is performed for that class).

Ideally I wouldn't have this config option but it is currently quite difficult to find a location to prepopulate this cache when running the SiteTree, although I'm open to suggestions here and more than happy to remove the configuration part of this PR.

Fixes #467

### CODE REVIEW

**Comment by sminnee** [comment]
Let's implement https://github.com/silverstripe/silverstripe-framework/issues/8391 and then refactor this PR to provide a `onPrepopulateTreeDataCache()` implementation on the FluentSiteTreeExtension.

**Comment by sminnee** [comment]
This should probably be committed to master / 4.2.x-dev

**Comment by sminnee** [comment]
A patch for this is here https://gist.github.com/bec52b2d0f50a42f44a0aea2a05bc2af

If you can give me commit rights to the creative-commoners repo I'll push it to this branch

File: src/Extension/FluentVersionedExtension.php [hunk 1]
```diff
@@ -329,4 +357,69 @@ public function flushCache()
...
+     * @param array $options A map of hints about what should be cached. "numChildrenMethod" and
+     *                       "childrenMethod" are allowed keys.
+     */
+    public function onPrepopulateTreeDataCache(DataList $recordList = null, array $options = [])
+    {
+        if (!Config::inst()->get(static::class, 'prepopulate_localecontent_cache')) {
+            return;
+        }
+
+        // This functionality hasn't been implemented; it's not actually used right now, so assumeYAGNI
```
Comment (robbieaverill) [inline src/Extension/FluentVersionedExtension.php]: Can we clarify this comment a bit? The end doesn't make sense to me

**Comment by ScopeyNZ** [comment]
I have updated the comment. I just translated the acronym 🙂

**Comment by robbieaverill** [comment]
Ok so is this PR dependant on https://github.com/silverstripe/silverstripe-framework/pull/8380? If so, we'll need to prepare a new minor release which has a 4.3 minimum in core, since that PR was merged into 4.3.x-dev

**Comment by ScopeyNZ** [comment]
Right. I can rebase this onto `4` in the morning...

**Comment by sminnee** [comment]
@robbieaverill @ScopeyNZ this doesn't _require_ 4.3+, but it's a no-op until 4.3 is installed. I don't think the constraint change is required then?

**Comment by robbieaverill** [comment]
OK sweet

**Comment by robbieaverill** [comment]
In that case there's no rebase required. It'd be cool to get Travis going before merge (I've pinged Damian), but if they pass locally then go for it

**Comment by sminnee** [comment]
I wonder if @tractorcow wants to invite some commoners to help till the farm?

File: src/Extension/FluentVersionedExtension.php [hunk 2]
```diff
@@ -304,21 +327,26 @@ protected function isLocalisedInStage($stage, $locale = null)
             $table .= self::SUFFIX_LIVE;
         }
 
+        if (isset(self::$idsInLocaleCache[$locale][$table])) {
+            return in_array($this->owner->ID, self::$idsInLocaleCache[$locale][$table]);
```
Comment (maxime-rainville) [inline src/Extension/FluentVersionedExtension.php]: Checking if an array key exists is a lot faster than checking if a value is present in array. Might be worthwhile restructuring `$idsInLocaleCache` to do that instead.

File: src/Extension/FluentVersionedExtension.php [hunk 3]
```diff
@@ -329,4 +357,70 @@ public function flushCache()
...
+     * Prepopulate the cache of IDs in a locale, to optimise batch calls to isLocalisedInStage.
+     *
+     * @param string $locale
+     * @param string $dataObject
+     */
+    public static function prepoulateIdsInLocale($locale, $dataObjectClass, $populateLive = true, $populateDraft = true)
+    {
+        // Get the table for the given DataObject class
+        $self = new static();
+        $table = $self->getLocalisedTable(Injector::inst()->get($dataObjectClass)->baseTable());
```
Comment (maxime-rainville) [inline src/Extension/FluentVersionedExtension.php]: Wouldn't you be better off getting a singleton of `$dataObjectClass` and calling `getLocalisedTable` on that.

```php
$singleton = DataObject::singleton($dataObjectClass);
$table = $singleton->getLocalisedTable();
```

**Comment by maxime-rainville** [comment]
Probably need to write some unit test for this as well.

File: src/Extension/FluentVersionedExtension.php [hunk 4]
```diff
@@ -304,21 +327,26 @@ protected function isLocalisedInStage($stage, $locale = null)
...
             '"RecordID"' => $this->owner->ID,
             '"Locale"' => $locale,
         ]);
-        $query->firstRow();
-        $result = $query->execute()->value() !== null;
+
+        $result = $query->firstRow()->execute()->value() !== null;
 
         // Set cache
         $this->localisedStageCache[$key] = $result;
```
[the remark this answers is not in the document]
Comment (ScopeyNZ) [reply src/Extension/FluentVersionedExtension.php]: The only reason I didn't do this is the static cache only knows about records that are localised - but it knows about all of them, so if it's missing then we can reliably say it is _not_ localised in the given stage. With the fallback, it caches either `true` or `false`. I can make the other one static too which should provide a little boost.

File: src/Extension/FluentVersionedExtension.php (hunk 2 above)
Comment (ScopeyNZ) [reply src/Extension/FluentVersionedExtension.php]: Good call! I'll change this

File: src/Extension/FluentVersionedExtension.php (hunk 3 above)
Comment (ScopeyNZ) [reply src/Extension/FluentVersionedExtension.php]: I can use the `singleton` method :+1: - I'll also grab a singleton of the extension instead... I don't think the `DataObjectSchema` method will give the same result as there's some additional logic in `FluentExtension::getLocalisedTable`?

File: src/Extension/FluentVersionedExtension.php [hunk 5]
```diff
@@ -329,4 +357,70 @@ public function flushCache()
...
     }
+
+    /**
+     * Hook into {@link Hierarchy::prepopulateTreeDataCache}.
+     *
+     * @param DataList $recordList The list of records to prepopulate caches for. Null for all records.
+     * @param array $options A map of hints about what should be cached. "numChildrenMethod" and
+     *                       "childrenMethod" are allowed keys.
+     */
+    public function onPrepopulateTreeDataCache(DataList $recordList = null, array $options = [])
```
[the remark this answers is not in the document]
Comment (robbieaverill) [reply src/Extension/FluentVersionedExtension.php]: If it accepts an array, won't the DataList type hint throw an error when you give it an array?

File: src/Extension/FluentVersionedExtension.php [hunk 6]
```diff
@@ -304,29 +331,97 @@ protected function isLocalisedInStage($stage, $locale = null)
...
+
+        self::prepoulateIdsInLocale(FluentState::singleton()->getLocale(), $this->owner->baseClass());
+    }
+
+    /**
+     * Prepopulate the cache of IDs in a locale, to optimise batch calls to isLocalisedInStage.
+     *
+     * @param string $locale
+     * @param string $dataObject
+     */
```
Comment (robbieaverill) [inline src/Extension/FluentVersionedExtension.php]: There's a couple of new arguments to add here now

File: src/Extension/FluentVersionedExtension.php (hunk 5 above)
[the remark this answers is not in the document]
Comment (ScopeyNZ) [reply src/Extension/FluentVersionedExtension.php]: Oh, apparently I didn't change this bit 🤦‍♂️

File: src/Extension/FluentVersionedExtension.php [hunk 7]
```diff
@@ -304,29 +332,99 @@ protected function isLocalisedInStage($stage, $locale = null)
             $table .= self::SUFFIX_LIVE;
         }
 
+        if (isset(static::$idsInLocaleCache[$locale][$table])) {
```
Comment (robbieaverill) [inline src/Extension/FluentVersionedExtension.php]: I feel like this isset check should include the owner's ID like the line below

**Comment by robbieaverill** [comment]
I've done a little bit of a refactor in order to unit test this easily, and have pushed some new tests. LGTM. I think @tractorcow's feedback has been addressed

**Comment by robbieaverill** [comment]
We don't have Travis set up on this org yet (cc @tractorcow)

@tractorcow if you don't think we've correctly addressed your comments feel free to ping us and we'll look more into it =)

File: src/Extension/FluentVersionedExtension.php (hunk 7 above)
Comment (ScopeyNZ) [reply src/Extension/FluentVersionedExtension.php]: The reason I didn't is because we know all the IDs that exist in the locale for that table - the absence of an ID implies it's not there. So items that _aren't_ in that stage/locale will skip this cache if you isset check the ID too.
